version: "3"

services:
  gitlab:
    container_name: gitlab
    image: ${image}
    restart: unless-stopped
    hostname: ${hostname}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${external_url}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${ssh_port}
        gitlab_rails['initial_root_password'] = '${root_password}'
        gitlab_rails['initial_shared_runners_registration_token'] = '${runner_token}'
        sidekiq['max_concurrency'] = ${sidekiq_max_concurrency}
        gitlab_rails['time_zone'] = '${time_zone}'
        gitlab_rails['lfs_enabled'] = ${lfs_enabled}
        
        #mail
        gitlab_rails['smtp_enable'] = ${smtp_enable}
        gitlab_rails['smtp_address'] = '${smtp_address}'
        gitlab_rails['smtp_port'] = ${smtp_port}
        gitlab_rails['smtp_authentication'] = '${smtp_authentication}'
        gitlab_rails['smtp_enable_starttls_auto'] = ${smtp_enable_starttls_auto}
        gitlab_rails['smtp_openssl_verify_mode'] = '${smtp_openssl_verify_mode}'
        gitlab_rails['smtp_tls'] = ${smtp_tls}
        gitlab_rails['smtp_pool'] = ${smtp_pool}
        gitlab_rails['smtp_ssl'] = ${smtp_ssl}
        gitlab_rails['smtp_force_ssl'] = ${smtp_force_ssl}
        gitlab_rails['gitlab_email_enabled'] = ${gitlab_email_enabled}
        gitlab_rails['smtp_password'] = '${smtp_password}'
        gitlab_rails['smtp_user_name'] = '${smtp_user_name}'
        gitlab_rails['gitlab_email_from'] = '${gitlab_email_from}'
        gitlab_rails['gitlab_email_reply_to'] = '${gitlab_email_reply_to}'
        user['git_user_email'] = '${git_user_email}'
        gitlab_rails['smtp_domain'] = '${smtp_domain}'
        gitlab_rails['gitlab_email_display_name'] = '${gitlab_email_display_name}'
        gitlab_rails['gitlab_email_subject_suffix'] = '${gitlab_email_subject_suffix}'
      TZ: ${time_zone}
    ports:
      - ${web_port}:${web_port}
      - ${ssh_port}:22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'

volumes:
  gitlab_config:
    name: gitlab_config
  gitlab_logs:
    name: gitlab_logs
  gitlab_data:
    name: gitlab_data
